// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-qLFKH_Y6XE5vRl_GUmSTWUSmJqF8yE',
    appId: '1:1006802078948:web:57c07e68465d283fa6f0f1',
    messagingSenderId: '1006802078948',
    projectId: 'my-chat-app-yuson',
    authDomain: 'my-chat-app-yuson.firebaseapp.com',
    storageBucket: 'my-chat-app-yuson.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFr6VnP0fhlgAwC6FcGikpxX_HxtZcXzc',
    appId: '1:1006802078948:android:e6d4c9a9c07081c8a6f0f1',
    messagingSenderId: '1006802078948',
    projectId: 'my-chat-app-yuson',
    storageBucket: 'my-chat-app-yuson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kIcy1z0JGOWdYmgF3fz93YKYE3Rcmlg',
    appId: '1:1006802078948:ios:5afcc0ecf6bf437ba6f0f1',
    messagingSenderId: '1006802078948',
    projectId: 'my-chat-app-yuson',
    storageBucket: 'my-chat-app-yuson.appspot.com',
    iosClientId: '1006802078948-0vigpsaabulf16gt3h85sgbi5dskr85l.apps.googleusercontent.com',
    iosBundleId: 'com.example.yusonChatApp',
  );
}
